services:
  myproject:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/myproject
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local"
    env_file:
      - .env_dev
    depends_on:
      - database

    restart: always

  database:
    image: postgres:16.1-alpine3.18
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env_dev
    ports:
      - '5432:5432'
    restart: always

volumes:
  postgres-data:



