services:
  myproject:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/myproject
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local"
    env_file:
      - .env_dev
    depends_on:
      - database
      - worker
    restart: always

  database:
    image: postgres:16.1-alpine3.18
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env_dev
    ports:
      - '5432:5432'
    restart: always

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always

  worker:
    build:
      context: .
    command: >
      sh -c "celery -A config worker -l INFO"
    restart: always
    depends_on:
      - redis

volumes:
  postgres-data:



